print ("")
art = input("What would you like to see in ASCII art? ")
print ("")
print ("")
if ( art == "square" ):
    print (" ––––––––––––––")
    print ("|              |")
    print ("|              |")
    print ("|              |")
    print ("|              |")
    print ("|              |")
    print ("|              |")
    print (" ––––––––––––––")
elif ( art == "rectangle" ):
    print (" –––––––––––")
    print ("|           |")
    print (" ––––––––––– ")
elif ( art == "hotdog" ):
    print ("    –––––––––––––––––––––––––")
    print (" , ––––––––––––––––––––––––––– ,")
    print ("|    ~~~~~~~~~~~~~~~~~~~~~~     |")
    print (" ‘ ––––––––––––––––––––––––––– ‘")
    print ("    –––––––––––––––––––––––––")
elif ( art == "potatowitheyes" ):
    print ("    ______")
    print ("  /        \ ")
    print (" |   º    º  \ ")
    print ("  |           \ ")
    print ("   –     -     \ ")
    print ("    |           |")
    print ("     \         /")
    print ("       –––––– ")
elif ( art == "toes" or art == "furryporn" ):
    print ("Go away, heathen")
elif ( art == "potato" ):
    print ("    ______")
    print ("  /        \ ")
    print (" |           \ ")
    print ("  |           \ ")
    print ("   –           \ ")
    print ("    |           |")
    print ("     \         /")
    print ("       –––––– ")
elif ( art == "peepee" or art == "penis" or art == "dick" or art == "cock" or art == "peen"):
    print (" ––––")
    print ("|    |")
    print ("|    |")
    print (" –––  ––––––––––––––––––––––––––––––|––\ ")
    print ("    |                               | __\ ")
    print ("    |                               |   /")
    print (" –––  ––––––––––––––––––––––––––––––|––/")
    print ("|    |")
    print ("|    |")
    print (" ––––")
elif ( art == "nut" ):
    print ("")
else:
    print ("Sorry, I can't draw that. Maybe try “square“, “rectangle”, “hotdog”, “furryporn“ or “potatowitheyes” next time")
print ("")
print ("")
